### ISSUE TITLE
Image compiles but doesn't boot

### ISSUE THREAD

**Issue by antoniograzioli** [simonvanderveldt/norns-image#32]
I created the norns.img with the instructiom you provided ("Simply run ./build.sh").
I got some warnings but no errors.
Flashed it with Balena, but my RPI3 doesn't seem to boot with it. I have tried with and without the DIY norns shield attached.
Maybe I'm just missing something?

**Comment by simonvanderveldt** [comment]
If you just ran `./build.sh` you've built an image for norns, not for the Raspberry Pi :)

To build an image for the Raspberry Pi3 you can run `./build.sh norns_raspberrypi3_defconfig`, I'll add this to the readme.

You can also download a prebuilt image from https://51-121434924-gh.circle-artifacts.com/0/norns-raspberrypi3.img

**Comment by antoniograzioli** [comment]
Ooops sorry for that. I strictly followed the instructions here :)
Noob question 😑 I’ll test the precompiled image then try to compile it again

**Comment by antoniograzioli** [comment]
the prebuilt image you linked works!
